#!/usr/bin/env bash
# init.sh — persist a profile.json from an interview-collected JSON document
# The LLM constructs the profile JSON and pipes it to this script.
# Usage: init.sh --profile-json <path> [--force]
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
PROFILE_DIR="$REPO_ROOT/.x-skills/x-qa"
PROFILE_PATH="$PROFILE_DIR/profile.json"
README_PATH="$PROFILE_DIR/README.md"
PROFILE_INPUT=""
FORCE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile-json) PROFILE_INPUT="$2"; shift 2 ;;
    --force) FORCE=true; shift ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

if [[ -z "$PROFILE_INPUT" ]]; then
  echo "✗ x-qa init FAILED" >&2
  echo "REASON=missing --profile-json argument" >&2
  exit 2
fi

if [[ -f "$PROFILE_PATH" ]] && [[ "$FORCE" != true ]]; then
  echo "✗ x-qa init FAILED" >&2
  echo "REASON=profile already exists at $PROFILE_PATH; use --force to overwrite or 'update' to reconcile" >&2
  exit 2
fi

# Validate input against schema invariants (delegates to doctor.sh in Task 9; for now, basic checks)
if ! jq -e '.schema == 1 and (.entry_points | length > 0)' "$PROFILE_INPUT" > /dev/null 2>&1; then
  echo "✗ x-qa init FAILED" >&2
  echo "REASON=input JSON fails schema basic validation (schema!=1 or no entry_points)" >&2
  exit 3
fi

mkdir -p "$PROFILE_DIR"
cp "$PROFILE_INPUT" "$PROFILE_PATH"

cat > "$README_PATH" <<EOF
# .x-skills/x-qa/

Profile-driven E2E QA configuration. Generated by \`x-qa init\`.

- \`profile.json\` — checked into repo. Shared across team.
- \`runs/\` — gitignored. Transient run outputs.
- \`cache/\` — gitignored. Scan cache for fast \`update\`.

## Manage

- \`/x-skills:x-qa update\` — reconcile profile after code changes
- \`/x-skills:x-qa doctor\` — validate
- \`/x-skills:x-qa run\` — execute QA

See [skills/x-qa/SKILL.md](../../skills/x-qa/SKILL.md).
EOF

# Update .gitignore in repo root if needed (idempotent — append only missing lines)
GITIGNORE="$REPO_ROOT/.gitignore"
[[ -f "$GITIGNORE" ]] || touch "$GITIGNORE"
# Append a sentinel header once, then per-line guard each pattern.
if ! grep -qxF '# x-skills runtime artifacts' "$GITIGNORE"; then
  printf '\n# x-skills runtime artifacts\n' >> "$GITIGNORE"
fi
for pattern in '.x-skills/*/runs/' '.x-skills/*/cache/' '.x-skills/*/state.local.json' '.x-skills/*/.lock'; do
  grep -qxF "$pattern" "$GITIGNORE" || echo "$pattern" >> "$GITIGNORE"
done

# Emit envelope (top-level vars — `local` is a function-only keyword)
primary=$(jq -r '.primary_entry_point' "$PROFILE_PATH")
count=$(jq -r '.entry_points | length' "$PROFILE_PATH")
verified=$(jq -r '[.entry_points[].verified] | if all then "true" elif any then "partial" else "false" end' "$PROFILE_PATH")

echo "✓ x-qa profile ready"
echo "PROFILE_PATH=$PROFILE_PATH"
echo "ENTRY_POINTS=$count"
echo "PRIMARY=$primary"
echo "VERIFIED=$verified"
