#!/usr/bin/env bash
# release.sh — free this worktree's registry slot.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
# shellcheck source=allocate-ports.sh
. "$SCRIPT_DIR/allocate-ports.sh"

QUIET=0
for arg in "$@"; do
  case "$arg" in
    --quiet) QUIET=1 ;;
    --help|-h) echo "release.sh — free this worktree's registry slot."; exit 0 ;;
    *) echo "release.sh: unknown flag: $arg" >&2; exit 1 ;;
  esac
done

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "x-worktree-isolate release: not inside a git work tree" >&2
  exit 1
fi
REPO_ROOT="$(git rev-parse --show-toplevel)"

xwi_acquire_lock || exit 1
trap 'xwi_release_lock' EXIT

xwi_release_slot "$REPO_ROOT"
xwi_clear_singleton_owners_for "$REPO_ROOT"

# Fix #10: only delete generated files when their first line matches the
# auto-generated header. Otherwise leave them alone and warn — the user may
# have a hand-authored compose.override.yml or .env.worktree.
GEN_HEADER='# Auto-generated by x-worktree-isolate'
maybe_remove() {
  local path="$1"
  [[ -f "$path" ]] || return 0
  local first
  first="$(head -n 1 "$path" 2>/dev/null || true)"
  if [[ "$first" == "$GEN_HEADER"* ]]; then
    rm -f "$path"
  else
    [[ "$QUIET" -eq 1 ]] || echo "x-worktree-isolate release: skipping $path (not auto-generated)" >&2
  fi
}
maybe_remove "$REPO_ROOT/compose.override.yml"
maybe_remove "$REPO_ROOT/.env.worktree"
# state.local.json is always ours; safe to remove.
rm -f "$REPO_ROOT/.worktree-isolate/state.local.json" 2>/dev/null || true

[[ "$QUIET" -eq 1 ]] || echo "✓ x-worktree-isolate released slot for $REPO_ROOT"
